### 기본적인 단축키

a = 위에 셀 추가 b = 아래 셀 추가 X = 셀 삭제 #코멘트시 markdown으로 속성 변경 

##### class는 객체지향프로그래밍의 한 부분 객체를 정의하는 데이터와 이를 활용하는 기능을 가질 수 있는 것 

In [10]:
a = 1; b = 2 
print(a)
print(b)

1
2


In [12]:
a = 1
b = 2
print(a) ; print(b)

1
2


a = 1 수학적인 = 기호가 아니라 a에 1을 집어 넣어준다는 것 
a와 b가 한 라인에 같이 쓰이려면 ;을 붙여줘야 오류가 나지 않음  
결과 값이 제대로 나오려면 print함수를 사용해 줘야 한다는 것 

In [2]:
type(a)

int

In [ ]:
int는 파이썬에서 정수를 말함

In [13]:
a = 1.0
type(a)

float

In [ ]:
float은 파이썬에서 소수부분까지를 말함 

In [18]:
a = 1.2 ; a = int(a); print(type(a)); print(a)

<class 'int'>
1


### a를 소수이나 이를 int로 설정하면 소수부분이 빠지고 결과 값이 나옴 

In [19]:
a = '123'; print(type(a))

<class 'str'>


str이란 문자열를 순서대로 줄을 지어 있는 것 

In [20]:
a = 'abc' ; print(type(a))

<class 'str'>


##### 0을 시작점으로 문자열을 나누어 찾아 볼 수 있다


### 이 각각의 요소를 인덱스 라고 한다 

In [21]:
a[0]

'a'

In [21]:
a[1]

'b'

In [22]:
a[2]

'c'

In [23]:
a[-1]

'c'

In [25]:
a = [1,2,'ab',[4,5]] ; print(type(a))

<class 'list'>


In [26]:
a(1)

TypeError: 'list' object is not callable

In [29]:
a = (1,2,'ab',[4,5]) ; print(type(a)) ; print(a[0])

<class 'tuple'>
1


()인 tuple도 자료 배열은 해놓지만 리스트와는 수정부분에서 차이가 있음 

#### list란 숫자나 자료들은 여러개 배열해 놓은 것 

### {}를 사용해야 한다 ()을 사용하지 않도록 주의

In [32]:
a[0]

1

In [34]:
a[-1][0]

4

In [24]:
a = '123'; a = list(a); print(a)

['1', '2', '3']


##### variable dictionary,  have to use { }, unlike list,

In [44]:
a = {"a" : "apple", "b" : "orange", "c" : 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


## 무엇 :  설명의 대상  말과 뜻처럼 사용되는 함수  

In [30]:
a=[(1,2,3), (3,8,0)];print(type(a))

<class 'list'>


turple이 안에 들어가도 []로 묶이면 결국 리스트로 분류됨 

In [ ]:
turple을 리스트에 넣으면 위와 같이 2*3의 행렬처럼 만들어 지는 것이다 
컴마를 중심으로 밑으로 간다 - 그렇다고 행렬이 아니다 성질이 다르다   - 또 다른 과정으로 행렬을 사용하려면 필요함을 암시 

In [31]:
import numpy as np 
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### import? 
type과 print는 이미 프로그램 안에 설정해 놓은 함수임 -
함수가 수천 수십만개가 들어있는데 전부다 그러한 함수가 있을까?
함수 모두를 설정 해 놓으면 너무 많으니 프로세스 오류 등의 야기 필요할 때 마다 그 패키지를 올려놓고 쓰면 된다. 
이러한 것을 메모리에 올려놓는 것을 import라고 한다. 
기본적인것으로 내재되있는 것들은 임폴트 필요 없다


## as는 그것처럼 말을 쓴다(줄임말)로 생각하면 됨 
## 'numpy.darray는 행렬처럼 생겼는데 과연 행렬일까? 

In [ ]:
print(b*b)

### 곱해짐을 알수 있음 행렬과 유사한 모습이나 행렬은 아니라는 것을 보여줌 

행렬이면 2*3/3*2 처럼 앞뒤가 맞아야 곱하기가 가능 / 이경우 각 원소끼리 서로 제곱승이 되는 결과를 보여줌 

In [37]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


### matrix 함수를 통해 행렬을 만들어낸다 

In [38]:
c * c 

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

조합이 맞지 않아 오류가 뜸

In [39]:
c*c.T 

matrix([[14, 19],
        [19, 73]])

t는 transpose를 말한다. 2 * 3 을 // 3 * 2 로 바꾸어주는 것 